In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
data=pd.read_csv(r"C:\Users\Shan\Downloads\Admission_Predict.csv")

In [4]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

# Training and Testing the model

In [5]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
268,269,327,113,4,4.5,5.0,9.14,0
208,209,305,106,2,3.0,3.0,8.16,0
49,50,327,111,4,3.0,4.0,8.40,1
196,197,306,105,2,3.0,2.5,8.26,0
148,149,339,116,4,4.0,3.5,9.80,1
...,...,...,...,...,...,...,...,...
199,200,313,107,3,4.0,4.5,8.69,0
386,387,302,101,2,2.5,3.5,7.96,0
68,69,318,109,3,3.5,4.0,9.22,1
144,145,325,112,2,3.0,3.5,8.96,1
277,278,320,101,2,2.5,3.0,8.62,0

In [6]:
y_train

268    0.83
208    0.64
49     0.78
196    0.73
148    0.96
       ...
199    0.72
386    0.46
68     0.68
144    0.80
277    0.70
Name: Chance of Admit , Length: 340, dtype: float64

In [7]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
150,151,334,114,4,4.0,4.0,9.43,1
389,390,320,108,3,3.5,4.0,8.44,1
155,156,312,109,3,3.0,3.0,8.69,0
193,194,336,118,5,4.5,5.0,9.53,1
335,336,325,111,4,4.0,4.5,9.11,1
223,224,308,109,2,3.0,4.0,8.45,0
104,105,326,112,3,3.5,3.0,9.05,1
147,148,326,114,3,3.0,3.0,9.11,1
190,191,324,111,5,4.5,4.0,9.16,1
312,313,311,107,4,4.5,4.5,9.00,1
281,282,317,110,3,4.0,4.5,9.11,1
246,247,316,105,3,3.0,3.5,8.73,0
197,198,310,106,2,3.5,2.5,8.33,0
241,242,317,103,2,2.5,2.0,8.15,0
154,155,326,108,3,3.0,3.5,8.89,0
243,244,325,114,3,3.5,3.0,9.04,1
267,268,314,107,3,3.0,3.5,8.17,1
128,129,326,112,3,3.5,3.0,9.10,1
97,98,331,120,3,4.0,4.0,8.96,1
378,379,303,98,1,2.0,2.5,7.65,0
57,58,298,99,2,4.0,2.0,7.60,0
344,345,295,96,2,1.5,2.0,7.34,0
123,124,308,108,3,3.5,3.5,8.22,0
342,343,308,106,3,3.0,3.0,8.24,0
140,141,329,110,2,4.0,3.0,9.15,1
9,10,323,108,3,3.5,3.0,8.60,0
141,142,332,118,2,4.5,3.5,9.36,1
347,348,299,94,1,1.0,1.0,7.34,0
86,87,315,106,3,4.5,3.5,8.42,0
365,366,330,114,4,4.5,3.0,9.17,1
66,67,327,114,3,3.0,3.0,9.02,0
34,35,331,112,5,4.0,5.0,9.80,1
180,181,300,104,3,3.5,3.0,8.16,0
118,119,296,99,2,3.0,3.5,7.28,0
328,329,324,112,4,4.0,3.5,8.77,1
396,397,325,107,3,3.0,3.5,9.11,1
380,381,322,104,3,3.5,4.0,8.84,1
3,4,322,110,3,3.5,2.5,8.67,1
33,34,340,114,5,4.0,4.0,9.60,1
372,373,336,119,4,4.5,4.0,9.62,1
282,283,312,106,3,4.0,3.5,8.79,1
391,392,318,106,3,2.0,3.0,8.65,0
272,273,294,95,1,1.5,1.5,7.64,0
353,354,300,102,3,3.5,2.5,8.17,0
122,123,310,106,4,1.5,2.5,8.36,0
300,301,309,106,2,2.5,2.5,8.00,0
290,291,307,105,2,2.5,3.0,7.65,0
315,316,308,104,2,2.5,3.0,8.07,0
6,7,321,109,3,3.0,4.0,8.20,1
308,309,312,108,3,3.5,3.0,8.53,0
239,240,299,100,1,1.5,2.0,7.89,0
195,196,307,107,2,3.0,3.5,8.52,1
310,311,320,104,3,3.0,3.5,8.74,1
77,78,301,99,2,3.0,2.0,8.22,0
259,260,331,119,4,5.0,4.5,9.34,1
366,367,320,104,3,3.5,4.5,8.34,1
126,127,323,113,3,4.0,3.0,9.32,1
116,117,299,102,3,4.0,3.5,8.62,0
384,385,340,113,4,5.0,5.0,9.74,1
233,234,304,100,2,2.5,3.5,8.07,0

In [8]:
y_test

150    0.93
389    0.76
155    0.77
193    0.94
335    0.83
223    0.71
104    0.74
147    0.83
190    0.90
312    0.78
281    0.80
246    0.72
197    0.73
241    0.65
154    0.80
243    0.76
267    0.73
128    0.84
97     0.86
378    0.56
57     0.46
344    0.47
123    0.61
342    0.58
140    0.84
9      0.45
141    0.90
347    0.42
86     0.72
365    0.86
66     0.61
34     0.94
180    0.71
118    0.47
328    0.80
396    0.84
380    0.78
3      0.80
33     0.90
372    0.95
282    0.81
391    0.71
272    0.49
353    0.63
122    0.57
300    0.62
290    0.58
315    0.65
6      0.75
308    0.69
239    0.59
195    0.78
310    0.76
77     0.64
259    0.90
366    0.74
126    0.85
116    0.56
384    0.96
233    0.64
Name: Chance of Admit , dtype: float64

# Model Evaluation

In [9]:
from sklearn.ensemble import GradientBoostingRegressor
model = GradientBoostingRegressor()
model.fit(x_train,y_train)

GradientBoostingRegressor()

In [10]:
GradientBoostingRegressor()

GradientBoostingRegressor()

In [11]:
model.score(x_test,y_test)

0.8840569185248338

In [12]:
y_predict=model.predict(x_test)

In [13]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error
import numpy as np
print('Mean Absolute Error:', mean_absolute_error(y_test, y_predict))  
print('Mean Squared Error:', mean_squared_error(y_test, y_predict))  
print('Root Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_predict)))

Mean Absolute Error: 0.033015616810317165
Mean Squared Error: 0.0022392828072763825
Root Mean Squared Error: 0.04732106092720642

In [14]:
y_train = (y_train>0.5)
y_test = (y_test>0.5)

In [15]:
from sklearn.linear_model._logistic import LogisticRegression

lore = LogisticRegression(random_state=0, max_iter=1000)

lr = lore.fit(x_train, y_train)

In [16]:
y_pred = lr.predict(x_test)
y_pred

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True])