# Training and Testing the model

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
data=pd.read_csv(r"C:\Users\Shan\Downloads\Admission_Predict.csv")

In [4]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [5]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']

In [6]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [7]:
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
371,372,324,110,3,3.5,3.0,9.22,1
82,83,320,110,5,5.0,4.5,9.22,1
135,136,314,109,4,3.5,4.0,8.77,1
331,332,311,105,2,3.0,2.0,8.12,1
374,375,315,105,2,2.0,2.5,7.65,0
...,...,...,...,...,...,...,...,...
88,89,314,108,3,4.5,3.5,8.14,0
191,192,323,110,5,4.0,5.0,8.98,1
17,18,319,106,3,4.0,3.0,8.00,1
8,9,302,102,1,2.0,1.5,8.00,0
26,27,322,109,5,4.5,3.5,8.80,0

In [8]:
y_train

371    0.89
82     0.92
135    0.82
331    0.73
374    0.39
       ...
88     0.64
191    0.87
17     0.65
8      0.50
26     0.76
Name: Chance of Admit , Length: 340, dtype: float64

In [9]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
303,304,323,107,3,3.5,3.5,8.55,1
98,99,332,119,4,5.0,4.5,9.24,1
208,209,305,106,2,3.0,3.0,8.16,0
128,129,326,112,3,3.5,3.0,9.10,1
176,177,329,119,4,4.5,4.5,9.16,1
102,103,314,106,2,4.0,3.5,8.25,0
81,82,340,120,4,5.0,5.0,9.50,1
381,382,319,105,3,3.0,3.5,8.67,1
251,252,316,99,2,2.5,3.0,9.00,0
236,237,325,112,4,4.0,4.5,9.17,1
246,247,316,105,3,3.0,3.5,8.73,0
110,111,305,108,5,3.0,3.0,8.48,0
118,119,296,99,2,3.0,3.5,7.28,0
215,216,330,116,5,5.0,4.5,9.36,1
232,233,312,107,2,2.5,3.5,8.27,0
328,329,324,112,4,4.0,3.5,8.77,1
73,74,314,108,4,4.5,4.0,9.04,1
181,182,305,107,2,2.5,2.5,8.42,0
172,173,322,110,4,4.0,5.0,9.13,1
4,5,314,103,2,2.0,3.0,8.21,0
360,361,322,110,3,4.0,5.0,8.64,1
397,398,330,116,4,5.0,4.5,9.45,1
76,77,327,112,3,3.0,3.0,8.72,1
69,70,328,115,4,4.5,4.0,9.16,1
84,85,340,115,5,4.5,4.5,9.45,1
273,274,312,99,1,1.0,1.5,8.01,1
241,242,317,103,2,2.5,2.0,8.15,0
233,234,304,100,2,2.5,3.5,8.07,0
116,117,299,102,3,4.0,3.5,8.62,0
227,228,312,110,2,3.5,3.0,8.53,0
189,190,324,112,5,5.0,5.0,9.08,1
145,146,320,113,2,2.0,2.5,8.64,1
321,322,323,104,3,4.0,4.0,8.44,1
27,28,298,98,2,1.5,2.5,7.50,1
53,54,324,112,4,4.0,2.5,8.10,1
375,376,304,101,2,2.0,2.5,7.66,0
356,357,327,109,3,3.5,4.0,8.77,1
15,16,314,105,3,3.5,2.5,8.30,0
313,314,301,100,3,3.5,3.0,8.04,0
1,2,324,107,4,4.0,4.5,8.87,1
238,239,310,104,3,2.0,3.5,8.37,0
275,276,322,110,3,3.5,3.0,8.96,1
305,306,321,109,3,3.5,3.5,8.80,1
92,93,298,98,2,4.0,3.0,8.03,0
339,340,324,107,5,3.5,4.0,8.66,1
378,379,303,98,1,2.0,2.5,7.65,0
44,45,326,113,5,4.5,4.0,9.40,1
385,386,335,117,5,5.0,5.0,9.82,1
187,188,335,118,5,4.5,3.5,9.44,1
104,105,326,112,3,3.5,3.0,9.05,1
334,335,312,107,4,4.5,4.0,8.65,1
37,38,300,105,1,1.0,2.0,7.80,0
304,305,313,106,2,2.5,2.0,8.43,0
254,255,321,114,4,4.0,5.0,9.12,0
282,283,312,106,3,4.0,3.5,8.79,1
165,166,322,110,5,4.5,4.0,8.97,0
352,353,303,100,2,3.0,3.5,8.06,1
143,144,340,120,4,4.5,4.0,9.92,1
70,71,332,118,5,5.0,5.0,9.64,1
261,262,312,104,3,3.5,4.0,8.09,0

In [10]:
y_test

303    0.73
98     0.90
208    0.64
128    0.84
176    0.90
102    0.62
81     0.96
381    0.73
251    0.70
236    0.85
246    0.72
110    0.61
118    0.47
215    0.93
232    0.69
328    0.80
73     0.84
181    0.71
172    0.86
4      0.65
360    0.85
397    0.91
76     0.74
69     0.78
84     0.94
273    0.52
241    0.65
233    0.64
116    0.56
227    0.64
189    0.88
145    0.81
321    0.73
27     0.44
53     0.72
375    0.38
356    0.79
15     0.54
313    0.67
1      0.76
238    0.70
275    0.78
305    0.74
92     0.34
339    0.81
378    0.56
44     0.91
385    0.96
187    0.93
104    0.74
334    0.73
37     0.58
304    0.62
254    0.85
282    0.81
165    0.78
352    0.64
143    0.97
70     0.94
261    0.71
Name: Chance of Admit , dtype: float64